apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    maxLoadingConcurrency: '2'
    opendatahub.io/accelerator-name: ''
    opendatahub.io/apiProtocol: REST
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: Custom Triton runtime 25.08
    opendatahub.io/template-name: custom-triton-2508
    openshift.io/display-name: ensemble-model
  name: ensemble-model

  namespace: demo
  labels:
    name: custom-triton-2508
    opendatahub.io/configurable: 'true'
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8002'
    prometheus.io/scrape: 'true'
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8001
    serverType: triton
  containers:
    - args:
        - '--model-repository=/mnt/models/'
        - '--model-control-mode=explicit'
        - '--strict-readiness=false'
        - '--allow-http=true'
        - '--allow-sagemaker=false'
        - '--load-model=*'
        - '--allow-metrics=true'
        - '--http-port=8080'
      command:
        - tritonserver
      image: 'quay.io/rh_ee_asathish/custom-tritonserver:v1.0.0'
      livenessProbe:
        exec:
          command:
            - curl
            - '--fail'
            - '--silent'
            - '--show-error'
            - '--max-time'
            - '9'
            - 'http://localhost:8080/v2/health/live'
        initialDelaySeconds: 5
        periodSeconds: 30
        timeoutSeconds: 10
      name: kserve-container
      volumeMounts:
        - mountPath: /mnt/models/
          name: local-model-repo
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  protocolVersions:
    - grpc-v2
    - v2
  supportedModelFormats:
    - autoSelect: true
      name: keras
      version: '2'
    - autoSelect: true
      name: onnx
      version: '1'
    - autoSelect: true
      name: pytorch
      version: '1'
    - autoSelect: true
      name: tensorflow
      version: '1'
    - autoSelect: true
      name: python
      version: '1'
    - autoSelect: true
      name: tensorrt
      version: '7'
    - autoSelect: true
      name: bls
      version: '1'
    - autoSelect: true
      name: ensemble
      version: '1'
    - autoSelect: true
      name: fil
      version: '1'
  volumes:
    - emptyDir: {}
      name: local-model-repo
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
